### ISSUE TITLE
Possiblity to download deps from within cmake and generate deb package

### ISSUE THREAD

**Issue by xor-gate** [ludocode/msgpack-tools#1]
It is possible to download dependencies from with cmake (you are using 2.6):
`file(DOWNLOAD url file [TIMEOUT timeout] [STATUS status] [LOG log])`

Docs for 2.6 are located here: https://cmake.org/cmake/help/cmake2.6docs.html

Have you had a look at it ?

**Comment by xor-gate** [comment]
I started working in #2

**Comment by xor-gate** [comment]
Actually, I wanted to create a debian package which is placed in our internal used Debian 8 development repo. Because for a long time it will probably not be in the debian upstream repo. Maybe you want to notify this software is available and usefull for other users where maintainers (archlinux,debian etc can integrate it). It is very easy because only cmake and c/c++ compiler is needed (except for the exotic man page generator).

**Comment by xor-gate** [comment]
Hi Nicolas (@ludocode),

I know you are a busy man, and did not yet have written any comments on this. Would you like this feature in the build system or not?

You could distribute binaries on the following platforms if you where unaware of these:
- https://packagecloud.io/
- https://bintray.com/

**Comment by ludocode** [comment]
Oops, looks like I lost track of this issue. Sorry about that! I am definitely interested in adding support for building a .deb package. I don't expect these tools to end up in distribution repos any time soon if ever, but it would certainly be useful to provide a pre-packaged deb (and maybe an Arch package) as part of the releases so that it doesn't need to be compiled.

I'll look into it this week. I was holding off on doing a v0.4 release of this until MPack 0.9 is released since it contains a lot of important stream fixes. For example piping netcat to msgpack2json will give you lots of errors, whereas it works if you build msgpack2json using the latest MPack develop branch. But MPack 0.9 sort of ballooned in terms of featureset and is unfortunately nowhere near release, so I really should update this to just fetch an MPack develop commit in the meantime.

I'm not sure if downloading dependencies as part of the CMake script is a good idea. The reason they are fetched separately right now is because the packages are included in the msgpack-tools release tarball, and the `fetch.sh` script is not included. There would be unused code to download them in the `CMakeLists.txt` release package. Same goes for the man pages; the troff man pages are in the release tarball and the `man.sh` script is not. Basically the dependencies aren't supposed to be fetched when you build msgpack2json; they should only be fetched if you want to modify msgpack2json itself, in which case you're building from the repo rather than a release package.

**Comment by xor-gate** [comment]
If you want to automate the release/build process and push binary packages (on tags) from travis it would be nice to automate this process. And of course there are files which should not be included into the package. You could also look at CPackRPM which builds RPM packages if you didn't know.

**Comment by ludocode** [comment]
As much as I'd like to automate the release process, I'm not sure if it's a good idea to build binary packages on Travis. Their container-based infrastructure is still stuck on Ubuntu 12.04. I would think that binary packages for each platform should be built on the target platform itself rather than trying to cross-compile everything from an old version of Ubuntu.

For such a small tool, it's probably a bad idea to provide binary packages at all actually. I would think that Homebrew or the AUR are the ideal type of distribution method. This doesn't have anywhere near the notability required for Homebrew though; they frown upon people submitting their own projects. I think I can add this to the AUR and provide a brew formula in the repo itself, so it can still be installed by Homebrew without pushing the formula upstream.

I'm not sure what to do about Ubuntu, Debian and Fedora though. Do they have something like the AUR to automate building packages from source with dependency checking? I looked into the process for building a .deb and it seems like it would be quite a bit of work even just to set it up, let alone doing releases.

**Comment by ludocode** [comment]
I've just released v0.4. I also added msgpack-tools to the AUR and provided a Homebrew formula for OS X. I'm open to suggestions on how to more easily install it on Debian/Ubuntu and Fedora. I'd like to avoid providing binary packages for each platform, so it would be ideal if they had something like Homebrew/AUR for installing from source.

If you do make a script to generate a .deb package for your internal use though I'd be interested in adding this to the `tools/` folder. This would make it available in release packages for a future release of msgpack-tools.

**Comment by xor-gate** [comment]
Hi nicolas, thanks for your work.

The current code I have at Dual Inventive is integrated into the PR:
https://github.com/ludocode/msgpack-tools/pull/2

We use CMake for most of the Debianze process and avoid 99% of the times some custom shell scripts.

**Comment by xor-gate** [comment]
>  I'm open to suggestions on how to more easily install it on Debian/Ubuntu and Fedora. I'd like to avoid providing binary packages for each platform, so it would be ideal if they had something like Homebrew/AUR for installing from source.

Yeah that is more pain than actually creating this handy tools. Having distro-specific files in your project which you may only use once-in-a-time (when not automating packaging) then you could better provide detailed instruction about dependencies and the build process for people who want to integrate this into their package manager (dpkg, rpm, pacman, pkg, apk, etcetera).

**Comment by xor-gate** [comment]
Hi Nicolas,

I have found somebody who had exactly the same problem to create a debian package for the other msgpack C++ binding library. This seems like a nice way to create a package:
https://techoverflow.net/blog/2013/08/08/how-to-create-msgpack-deb-packages/

**Comment by xor-gate** [comment]
Very nice, maybe when people download release zipfiles you can create a .version file and fetch it with CMake when the current folder has no git tag like Nanomsg does in their top level CMakeLists.txt: https://github.com/nanomsg/nanomsg/blob/master/CMakeLists.txt#L59-L88

You must make sure you create annotated release tags then.

**Comment by ulikoehler** [comment]
@xor-gate @ludocode I'm the author of the TechOverflow blog and if you're still interested in this, the build script has been merged into my [deb-buildscripts](https://github.com/ulikoehler/deb-buildscripts) repository. If you have special requirements for the deb package, I'll be happy to implement them.
