### ISSUE TITLE
"Top level object must be a map or array" - why?

### ISSUE THREAD

**Issue by Qix-** [ludocode/msgpack-tools#3]
With the data

```
a2 4f 4b
```

I get

```
msgpack2json: Top-level object must be a map or array. Try debug viewing mode (-d)
mpack breakpoint hit at /tmp/msgpack-tools-20160714-1642-vla6bf/msgpack-tools-0.4/contrib/mpack-8c13a0d7f8a1232a189634768b94740861cbaf3e/src/mpack/mpack-common.c:321
```

But _why_? A single string `"OK"` is valid JSON, technically speaking. As well, MessagePack's [specification](https://github.com/msgpack/msgpack/blob/master/spec.md) doesn't enforce that - let alone does it even mention top level objects.

For instance, running just the string `"OK"` through `jq` gives me perfectly normal output.

``` console
$ echo "\"OK\"" | jq ''
"OK"
```

**Comment by ludocode** [comment]
Hmm. So, this is not a requirement of MessagePack, but it _was_ a requirement of JSON. `"ok"` is a valid JSON value (or object name), but was not a valid JSON document, or "JSON text" as per the original spec. The converter is expecting to produce a complete document, so it wants an object or array. This was specified in the original RFC:

https://tools.ietf.org/html/rfc4627

> A JSON text is a serialized object or array.
> 
> ```
>  JSON-text = object / array
> ```

Apparently this requirement has been dropped from the JSON spec though. JSON has done away with the document/text requirement altogether, instead just defining JSON values. The new RFC obsoletes the above and only talks about values:

https://tools.ietf.org/html/rfc7158

>    o  Changed the definition of "JSON text" so that it can be any JSON
>      value, removing the constraint that it be an object or array.

So that's good news. I'll put out an update soon to remove this requirement.

**Comment by Qix-** [comment]
Sounds great :) Thanks for the information! I had forgotten about the document requirement in the JSON spec.

Looking forward to the update! These tools are very useful.

**Comment by Qix-** [comment]
Thank you!!
